### ISSUE TITLE
main Login/Password 

### ISSUE THREAD

**Issue by rtemanni** [iohenkies/iskylims_docker#1]
Hi
Thank you for taking the time to create the container.
it working fine and all steps install correctly!
What login/password to Log into iSkyLIMS ?
Best,
Ramzi

**Comment by iohenkies** [comment]
Oh my, I totally missed that. I've edited the readme. Could you try with the new steps?

**Comment by rtemanni** [comment]
Thank you for adding the missing step.
Now it's working and I'm able to access it.
